### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by josh9060** [codejamninja/login-ui#1]
Hi,

Does this utilise PKCE as its a public client?

Did you create a custom login provider here (that managed your users and authenticated them): `${config.services.identityApi}/auth/login`?

**Comment by clayrisser** [comment]
@Joshgallagher I am sorry but I don't maintain this project anymore. I have moved on to use keycloak as my identity and oauth provider. As far as I can remember I used PKCE, but I'm a little fuzzy on it so I can't remember. I followed the instructions hydra put in their docs as close as I could.

The login provider I created can be found at the link below.
https://github.com/codejamninja/loopback4-hydra
